[package]
name = "blockery-rs"
version = "0.1.0"
authors = ["municorn <municorn@musicaloft.com>"]
edition = "2018"

[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] }
cgmath = "0.17"
rand = "0.7"
